### ISSUE TITLE
How to modify block interaction for all players in claimed areas?

### ISSUE THREAD

**Issue by Cixon** [FTBTeam/FTB-Chunks#101]
No. I don't want allies nor to unclaim the chunk.
I want everyone to only be able to interact with buttons and doors AND **NOT** to block edit.

Regarding a line found in \world\data\ftbchunks\ {uuid}.json
"groups":{},"allies":[],"block_edit_mode":"allies","block_interact_mode":**"???"**

What would I change the **block_interact_mode:**  ?
Allies is the only option I see written in this json file. Perhaps someone has the options?

**Comment by Cixon** [comment]
Thinking of changing it to "block_interact_mode":"all" may work but I didn't make this mod and there's not enough information as to how I could approach this or a feature that I know of to execute it this way.

**Comment by EnterFor** [comment]
I want to know too....

**Comment by Cixon** [comment]
Tested everything I could. I don't think this is a feature yet. Perhaps the Dev team could implement this in the future?

**Comment by SNVCK** [comment]
I spent 8 hours today scouring the web for an answer. My familiarity with this is minimal on a good day, but maybe you can fill in the gaps I have.
I believe by using FTB Ranks in conjunction with FTB Chunks, there is a way to set permissions. In your world folder > server configs, there is an FTB Chunks file that says you can override max/min chunk claims through FTB Ranks. All the permissions examples I found were for utilities which is useless for 1.16.4/1.16.5, so that is where I’m at a loss. I don’t know if permissions in that category exist yet, or maybe I formatted it incorrectly, but I’m trying to allow all members on the server to use buttons and doors as well (and hopefully Markets and Trading Posts from a separate mod). Hopefully that info is of some use and this gets resolved soon.

**Comment by ZEROX7** [comment]
so just found the solutionmy situation was that i wanted to protect a area from all players while giving them the ability to interact,
waht i did:
claim with a new player the area copy the data after the chunk in the players jason file inside /world ftbchunks data to the server json and setting the interaction setting to public
