### ISSUE TITLE
Chunkloaded chunks don't always unload

### ISSUE THREAD

**Issue by jinkhya** [FTBTeam/FTB-Chunks#145]
Hello,
I'm having a rather weird issue, sometimes chunks don't stop chunkloading. 
chunk_load_offline is set to false

I dunno if it's scheduled server restarts doing it, or kick on idle players or something else as it seems to be an inconsistent bug but I have nothing else chunkloading than ftb chunks and today, as I logged back in the server after 24 hours of being offline, I had tons of resources that I didn't have when I logged off. It didn't happen to me before, but some players did express that sometimes their base was staying loaded. 

Thanks, 
Jin

**Comment by jinkhya** [comment]
To add a pointer, could it be because of the idle setting in server.properties? If somebody gets kicked after the amount of minutes set, does it actually unloads those chunks? And/or, if server crashes does it mark chunks unloaded as well?

**Comment by Tander** [comment]
I have the same issue for months! On different modpacks!

From my experience, it may happen when server restarts. It looks like, after server restart all chunks are loaded even if nobody is online. But it's really difficult to diagnose, since admins don't have proper tools to see which chunks are loaded at the moment and why.

And no, I don't use idle setting in server.properties and have the same issue.
