### ISSUE TITLE
Add mob spawning flag for teams claim

### ISSUE THREAD

**Issue by LatvianModder** [FTBTeam/FTB-Chunks#21]
https://github.com/FTBTeam/FTB-Utilities/issues/898

**Comment by Seathre** [comment]
Was this flag ever added?

**Comment by NightcoreIsla** [comment]
infact,most modpack have something like megatorch
or even rftool environment machine
so i think that suggest maybe not really useful.
build guard system is a enjoy too

**Comment by TrinaryAtom** [comment]
I would absolutely love the ability to block mobs from spawning in any claimed chunk. Either given to individual players or team chunks. This would be great for allowing server owners or individual players to setup areas of the world as safe havens. All without having to bend over backwards to place modded resources then hiding them to maintain aesthetics, or, players who have to place a grid of vanilla torches if those options are not available in the current mod pack.

Back in 1.7, I used to create server scripts that would execute for players once they had any WorldGuard regions. This script would automatically place the 'no hostile mobs' flag on any of their owned regions.

In the end it makes minecraft feel a tad more immersive in my opinion. Go out side your home point, within your walls, and have lights appropriately placed on road corners, housing porches, gates, etc. Instead of them being thrown everywhere like a bunch of weeds.

I get their are other options to preventing mob spawning, but, none that use the incredibly intuitive interface of FTB Chunks.
