### ISSUE TITLE
Allotment of chunks at 0 and certain mods won't ally

### ISSUE THREAD

**Issue by DeathOfTime** [FTBTeam/FTB-Chunks#42]
I am playing ATM6 modpack. On their official server. With a recent update I have ran into a issue where I had 9 of 0 force loaded. when i brought the chunks down to 0 of 0 I could no longer force load chunks.

Three different mods, including Modular Routers, are no longer allied to me. It is saying they need to accept my invite. When I go to the bottom of the Allies list I can green check mark the [Mudular Routers] fake player. But further up the list is another [Modular Routers] that hasn't accepted my invite yet.

I've been trying to get help from the ATM team with this. They think it is a FTB Chunks issue. So I thought I might report it here. Just in case. Sorry if I am wasting your time.

**Comment by Scarlet-Phonavis** [comment]
Adding on to the second part, I'd like to request one way allying comes back as a setting or something for scenarios like this so no one has to maintain a list of fake real players or something. I'm sure the ability to one way trust a player also has its uses, though I can't think of one.

To be specific for anyone who finds this report and doesn't understand, allying is currently enforced as a 2 way street. If player one allys player 2 it does not take effect until player 2 returns the ally request to player 1 (and at the same time player 1 gets access to player 2's claims). It wasn't this way in older versions of FTB Util which is why this is suddenly a problem. 

Also OP, the first one more than likely isn't an issue, they probably turned force chunks for your rank to 0, aka mod acting as intended.

**Comment by DeathOfTime** [comment]
> Also OP, the first one more than likely isn't an issue, they probably turned force chunks for your rank to 0, aka mod acting as intended.

Yeah, sorry i didn't update this. It turned out that the server admins had turned off forced chunk loading to try and fix a tps issue they are having. I am still experiencing the issue with fake players not wanting to ally with me.

**Comment by cornholio84** [comment]
I too have a problem with modular routers and allying, cyclic works fine though.
Kind of strange of atm to add it in and is not even working in claimed chunks

**Comment by DeathOfTime** [comment]
It was working when I originally started playing the pack. It broke at the same time they dropped the forced chunks on the server to 0. That is why I thought the two related. Especially since it all happened at the time of one of their updates

**Comment by MaxNeedsSnacks** [comment]
Is this still an issue in the newest version of the pack? If so, feel free to reopen!
